window.ESTATEMOTION_ENV = {
  MOCK_AI: true,
  MOCK_RENDERING: true,
  MOCK_STRIPE: true,
  MOCK_SUPABASE: true,
  SUPABASE_URL: "",
  SUPABASE_ANON_KEY: "",
  LISTING_PHOTOS_BUCKET: "listing-photos",
  SUPABASE_STORAGE_PRIVATE: false,
  SUPABASE_SIGNED_URL_TTL_SECONDS: 172800,
  OPENAI_ENDPOINT: "",
  VISION_CLASSIFICATION_ENDPOINT: "/api/classify-image",
  STRIPE_PUBLISHABLE_KEY: "",
  STRIPE_CHECKOUT_ENDPOINT: "",
  RENDER_ENDPOINT: "",
  SUPABASE_JS_URL: "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm",
  ...(window.ESTATEMOTION_ENV ?? {})
};
