// EstateMotion — per-style color grade resolver.
//
// Single source of truth for the per-style 3D LUT system introduced in v23.
// Both the Runway pipeline (runway-job.mjs, applied per-clip during normalize)
// and the Remotion pipeline (render-job.mjs, applied as a post-render pass on
// the master MP4) use buildColorGradeFilter() so every render — regardless of
// engine — gets the same look for the same selected style.
//
// LUT files are generated by render-worker/scripts/generate-luts.mjs and live
// at render-worker/luts/<slug>.cube. To re-tune a look:
//   1. Edit the math in scripts/generate-luts.mjs
//   2. Re-run `node render-worker/scripts/generate-luts.mjs`
//   3. Commit both the script and the regenerated .cube files
//
// If a .cube file is missing on disk, we fall back to the legacy math grade
// so deploys that didn't pick up the LUT files still produce reasonable
// output rather than crashing the render entirely.

import path from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const LUTS_DIR = path.resolve(__dirname, "..", "luts");

// Legacy math grade — kept as a safety fallback. Was the only grade up
// through v22 and produced acceptable (if undifferentiated) output.
export const COLOR_GRADE_LEGACY =
  "eq=contrast=1.08:saturation=0.95:gamma=1.03,colorbalance=rs=0.05:bs=-0.025,unsharp=5:5:0.6:3:3:0.3";

// Sharpening pass — a separate axis from color grading. Always applied
// after the LUT (or in place of it, if we're on the legacy path).
export const UNSHARP_FILTER = "unsharp=5:5:0.6:3:3:0.3";

// Style slug → LUT file name. Multiple aliases per slug because we've
// shipped the style selector in different cosmetic forms over time
// ("MLS Clean", "mls-clean", "mls" all map to mls.cube).
const STYLE_LUT_MAP = {
  luxury: "luxury.cube",
  viral: "viral.cube",
  social: "viral.cube", // legacy alias
  mls: "mls.cube",
  "mls-clean": "mls.cube",
  "mls clean": "mls.cube",
  investor: "investor.cube"
};

// Pull the style slug from the various manifest shapes we've used over
// time. Normalize to lowercase + trimmed so "MLS Clean " === "mls-clean".
export function resolveStyleSlug(manifest) {
  const raw =
    manifest?.selectedStyle ||
    manifest?.template?.style ||
    manifest?.template?.styleSlug ||
    manifest?.style ||
    manifest?.musicMood ||
    "luxury";
  return String(raw).trim().toLowerCase();
}

// Resolves the absolute path to the LUT file for the current style.
// Returns null if the style isn't mapped or the file isn't on disk.
export function resolveLUTPath(manifest) {
  const slug = resolveStyleSlug(manifest);
  const lutFile = STYLE_LUT_MAP[slug];
  if (!lutFile) return null;
  const lutPath = path.join(LUTS_DIR, lutFile);
  if (!existsSync(lutPath)) return null;
  return lutPath;
}

// Build the ffmpeg video filter chain for color grade + sharpen.
// Returns a string suitable for use in -vf or as a node in -filter_complex.
//
//   buildColorGradeFilter(manifest)
//     → "lut3d=file='/abs/path/to/luxury.cube',unsharp=5:5:0.6:3:3:0.3"
//
// On missing LUT, falls back to COLOR_GRADE_LEGACY (which already includes
// its own unsharp pass — so we don't double-sharpen on the fallback path).
export function buildColorGradeFilter(manifest, options = {}) {
  const lutPath = resolveLUTPath(manifest);
  if (!lutPath) {
    if (options.verboseLog) {
      console.warn(
        `[color-grade] no LUT for style="${resolveStyleSlug(manifest)}" — using legacy math grade`
      );
    }
    return COLOR_GRADE_LEGACY;
  }
  // ffmpeg filter argument escaping:
  //   - Forward slashes only (Windows backslashes break the parser)
  //   - Colons are filter-arg separators; escape any in the path
  //     (Windows drive letters; macOS/Linux paths typically have none)
  const ffPath = lutPath.replace(/\\/g, "/").replace(/:/g, "\\:");
  return `lut3d=file='${ffPath}',${UNSHARP_FILTER}`;
}

// Convenience: returns a brief human-readable summary for logs.
export function describeColorGrade(manifest) {
  const slug = resolveStyleSlug(manifest);
  const lutPath = resolveLUTPath(manifest);
  return lutPath
    ? `3D LUT (${slug}, ${path.basename(lutPath)})`
    : `legacy math grade (no LUT for style="${slug}")`;
}
